export interface Progress {
  id?: string;  // Auto-generated by Supabase
  student_id: string;  // References auth.users.id
  class_id: string;    // References classes.id
  subject: string;
  score: number;
  max_score: number;
  assignment_name: string;
  date: string;  // ISO date string
  comments?: string;
  created_at?: string;  // Auto-generated by Supabase
  updated_at?: string;  // Auto-generated by Supabase
}

// This is the type for creating a new progress record (omits auto-generated fields)
export type NewProgress = Omit<Progress, 'id' | 'created_at' | 'updated_at'>;

// Table name in Supabase will be 'progress' (lowercase, singular by convention)
// Make sure to create this table in your Supabase database with appropriate columns
// that match the Progress interface above.
