import { ROLES, type UserRole } from '@/config/env';

export interface IUser {
  id?: string;  // Auto-generated by Supabase
  supabase_id: string;  // Matches Supabase auth.users.id
  email: string;
  name: string;
  role: UserRole;
  class_id?: string;  // References classes.id
  created_at?: string;  // Auto-generated by Supabase
  updated_at?: string;  // Auto-generated by Supabase
}

// This is the type for creating a new user record (omits auto-generated fields)
export type NewUser = Omit<IUser, 'id' | 'created_at' | 'updated_at'>;

// This is the type for updating a user record (makes all fields optional and omits some)
export type UserUpdate = Partial<Omit<IUser, 'id' | 'created_at'>> & { id: string };

// Table name in Supabase will be 'users' (lowercase, plural by convention)
// Make sure to create this table in your Supabase database with appropriate columns
// that match the IUser interface above.
